version: '3.8'

services:
  node-mcp-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-mcp-bridge
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:3001"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - PORT=3001
      - SETTINGS_PATH=/app/config/mcp-settings.json
      - SESSIONDB_PATH=/app/data/sessiondb.json
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NODE_ENV=${NODE_ENV:-production}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s